### ISSUE TITLE
Cannot play movie when movie name base64 encode result contains '/'

### ISSUE THREAD

**Issue by krizex** [dplesca/go-omxremote#3]
Since base64 encode may contain '/', it may cause following match failure:

> https://github.com/krizex/go-omxremote/blob/master/go-omxremote.go#L104
`router.POST("/start/:name", Start)`

I have met this issue and I think it's better to use base32 instead of base64.

**Comment by krizex** [comment]
I have tested PR #4 and it works fine.

**Comment by dplesca** [comment]
Hi, thanks for the reporting and the fix. I'll check it out as fast as I can and merge it in if everything is alright on my end.

**Comment by dplesca** [comment]
Thank you for the PR. It has been merged now.

**Comment by krizex** [comment]
^_^
		

		
	





On Fri, Jul 21, 2017 at 11:50 PM +0800, "Dragos Plesca" <notifications@github.com> wrote:












Thanks you for the PR. It has been merged now.
